name: ci-build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: 
        - ubuntu-18.04
        env:
        - DOCKER_IMG=archlinux
        - DOCKER_IMG=fedora-31

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world! ${DOCKER_IMG}
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
