name: ci-build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        docker_img: [ archlinux ]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world! ${{ docker_img }}
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
